version: "3.8"

services:
  app:
    image: rss-feed-front
    build: 
      context: ./rss-feed-front
      dockerfile: Dockerfile
    ports:
      - 5173:5173

  server:
    image: rss-feed-back
    build: 
      context: ./rss-feed-back
      dockerfile: Dockerfile
    ports:
      - 3001:3001